title: "dcがいかに素敵なプログラミング言語であるか伝えたい "
summary: "プログラミング言語 dc の紹介"
topics:
  - dc
  - プログラミング言語
published: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - preface
  - intro
  - commands
  - stack
  - commands-stack
  - commands-calc
  - commands-exec
  - registers
